name: Receive PR

# read-only repo token
# no access to secrets
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:   
      - name:Checkout
        uses: actions/checkout@v3
      - name: Change BASE_PATH
        run: yq -i '.JB.BASE_PATH = "https://saillantnicolas.github.io/cgal-web"' _config.yml
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
