name: Receive_PR

on: [pull_request,workflow_dispatch]

concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:   
      - name: Checkout
        uses: actions/checkout@v3
      - name: Change BASE_PATH
        run: yq -i '.JB.BASE_PATH = "https://cgal.github.io/cgal-web"' _config.yml
      - name: Remove demo/ (temporarily)
        run: rm -rf demo/
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Create PR number file
        run: |
          echo "PR number: ${{ env.GITHUB_EVENT_NUMBER }}" > pr_number.txt
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
      - name: Upload PR number file
        uses: actions/upload-artifact@v2
        with:
          name: pr_number
          path: pr_number.txt

